import {createSlice, PayloadAction} from '@reduxjs/toolkit';

// Define the interface for the state of the slice
export interface RouteProps {
  stateRoute: string;
}

// Define the initial state for the slice
const initialState: RouteProps = {
  stateRoute: '',
};

// Create a Redux Toolkit slice with the name 'stateRoute'
const routeSlice = createSlice({
  name: 'stateRoute',
  initialState,
  reducers: {
    // Reducer function to set the state route
    setRoute: (state, action: PayloadAction<string>) => {
      state.stateRoute = action.payload;
    },
  },
});

// Extract the action creator from the slice
export const {setRoute} = routeSlice.actions;

// Export the reducer function generated by the slice
export default routeSlice.reducer;
