import {createSlice, PayloadAction} from '@reduxjs/toolkit';
// Define the interface for the state of the slice
export interface TotalPriceProps {
  price: string;
}

// Define the initial state for the slice
const initialState: TotalPriceProps = {
  price: '',
};

// Create a Redux Toolkit slice with the name 'searchTitle'
const totalPriceSlice = createSlice({
  name: 'totalPrice',
  initialState,
  reducers: {
    // Reducer function to set the total price
    setTotalPrice: (state, action: PayloadAction<string>) => {
      state.price = action.payload;
    },
  },
});

// Extract the action creator from the slice
export const {setTotalPrice} = totalPriceSlice.actions;

// Export the reducer function generated by the slice
export default totalPriceSlice.reducer;
